server:
  port: 8081

jwt:
  secret: qwertyuiopasdfghjklzxcvbnmqwerty
#spring:
#  application:
#    name: content-service
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    timezone: GMT+8
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848
#      username: nacos
#      password: nacos
#  datasource:
#    url: jdbc:mysql://localhost:3306/share?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
#    hikari:
#      username: root
#      password: 123
#      driver-class-name: com.mysql.cj.jdbc.Driver



#spring:
#  application:
#    name: content-service
#  cloud:
#    nacos:
#      config:
#        server-addr: localhost:8848
#        file-extension: yml
#        namespace: test
#        group: DEFAULT_GROUP
#        timeout: 5000
#        config-long-poll-timeout: 10000
#        config-retry-time: 2000
#        max-retry: 3
#        refresh-enabled: true
#        extension-configs:
#          - dataId: redis-config.yml
#            group: EXT_GROUP
#            refresh: true

#  datasource:
#    url: jdbc:mysql://localhost:3306/share?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
#    hikari:
#      username: root
#      password: 123
#      driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    com.stf.content.openfeign.UserService: debug

#spring:
#  sleuth:
#    sampler:
#      # 采样率的概率，100%采样
#      probability: 1.0
#      # 每秒采样数字最高为1000
#      rate: 1000
#  zipkin:
#    sender:
#      type: rabbit
#    rabbitmq:
#      addresses: localhost:5672
#      queue: zipkin

#
#feign:
#  circuitbreaker:
#    enabled: true
#  client:
#    config:
#      default:
#        connectTimeout: 1000
#        readTimeout: 3000
#      user-service:
#        connectTimeout: 1000
#        readTimeout: 3000


services:
  database.com: localhost:3306
  nacos.com: localhost:8848
  web-server.com: localhost:8081
  gateway-server.com: localhost:8083