server:
  port: 8082

spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        heart-beat-interval: 5000
        heart-beat-timeout: 20000
        namespace: dev
        register-enabled: true
        username: nacos
        password: nacos


jwt:
  securt: qwertyuiopasdfghjklzxcvbnmqwerty