server:
  port: 8082
spring:
  sleuth:
    sampler:
      # 采样率的概率，100%采样
      probability: 1.0
      # 每秒采样数字最高为1000
      rate: 1000
  zipkin:
    sender:
      type: rabbit
    rabbitmq:
      addresses: localhost:5672
      queue: zipkin
#spring:
#  application:
#    name: user-service
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    timezone: GMT+8
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848
#      username: nacos
#      password: nacos
#
#    sentinel:
#      transport:
#        port: 8719
#        dashboard: http://localhost:8080
#  datasource:
#    url: jdbc:mysql://localhost:3306/share?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
#    hikari:
#      username: root
#      password: 123
#      driver-class-name: com.mysql.cj.jdbc.Driver

